### ISSUE TITLE
moondream LLM returns error with ollam-app

### ISSUE THREAD

**Issue by fliker09** [JHubi1/ollama-app#47] opened 2024-09-27 23:58 UTC
### Requirements

- [X] I have searched the issues of this repository and believe that this is not a duplicate
- [X] I have confirmed this bug exists on the latest version of the app

### Platform

Android

### Description

moondream LLM returns error with ollam-app

### Steps to reproduce

1. Run ollama with moondream LLM
2. Choose the image
3. Give the prompt
4. Send the prompt
![Screenshot_20240928-023254](https://github.com/user-attachments/assets/cf3385a6-2b1b-484b-8c7a-df314d7877d6)

### Expected behavior

A response from moondream LLM.

### Actual behavior

It thinks for a long time (minutes) and return the error.
![Screenshot_20240928-023419](https://github.com/user-attachments/assets/58cc4b56-512e-4ab0-80ad-766de7b50db0)

### Screenshots or additional context

No error seen on ollama side, except for this warning: "multimodal models don't support parallel requests yet".

**Comment by JHubi1** [comment] 2024-09-28 07:36
Server issue without actually having one suggests it being a timeout error. Please open Settings > Interface > Timeout multiplicator and set it to 10 for testing. Does that solve the issue?

**Comment by fliker09** [comment] 2024-09-28 09:50
It actually... helped! And the weirdest thing - it didn't take longer than to show the error like previously! Btw, adding timestamps to the messages would be a nice addition ^_^
Ok, it works now, but found a different issue - it seems that the second image is not sent (or maybe it's LLM's issue?):
![Screenshot_20240928-115553](https://github.com/user-attachments/assets/13f13434-a7ff-4884-ba8c-b6572afa0060)
I had to open a new chat for it to work properly:
![Screenshot_20240928-115805](https://github.com/user-attachments/assets/a976f138-0008-4934-81a2-d39b8d1d27b4)

**Comment by JHubi1** [comment] 2024-10-07 04:31
Please open a new issue, this isn't related. And close this one if the problem is solved

**Closed** 2024-11-10 09:36 UTC
Labels: bug
